import { OnInit, AfterViewInit } from '@angular/core';
import { Log } from './../../models/log.model';
import { LogStatus } from './../../models/log-status.enum';
import { TbLoggerService } from './../../services/tb-logger.service';
export declare class LoggerViewerComponent implements OnInit, AfterViewInit {
    loggerService: TbLoggerService;
    appIdInput: any;
    appId: string;
    appList: any;
    appData: Array<string>;
    app: string;
    appTypeList: any;
    appTypeData: Array<string>;
    appType: string;
    logs: Log[];
    logStatus: typeof LogStatus;
    show: boolean;
    loading: boolean;
    howMany: number;
    checked: boolean;
    autoRefresh: boolean;
    autoRefreshInterval: any;
    message: string;
    loggerUrl: any;
    constructor(loggerService: TbLoggerService);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    appListInit(): boolean;
    getLogs(): void;
    setLoggerUrl(event: any): void;
    setApp($event: any): void;
    setAppId($event: any): void;
    setAppType($event: any): void;
    close(): void;
    checkAutoRefresh(event: any): void;
}
